### ISSUE TITLE
Which DCF77 library?

### ISSUE THREAD

**Issue by zoomx** [Tsjakka/WeatherStation#1]
Wich DCF77 library was used?
The one written by udoklein support AVR and STM32F1 architecture but not ESP32, it gives 
```
exit status 1
#error Unsupported controller architecture
```

**Comment by Tsjakka** [comment]
That would be DCF77 by Thijs Elenbaas v1.0.0.

**Comment by zoomx** [comment]
So this one

[](https://github.com/thijse/Arduino-DCF77/releases/tag/1.0.0)
https://github.com/thijse/Arduino-DCF77/releases/tag/1.0.0

Thanks
